"""
Django settings for minicrm project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-a6jsq^!0$#0!l#!%rwh=02zc6^@rts_4y%@wzv295n^5nc98(i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS configuration
# In Kubernetes, health probes come from pod IPs, so we need to allow them
# For production, set ALLOWED_HOSTS env var with your domain(s)
# For Kubernetes, we allow all hosts to ensure health checks work
# Check if we're running in Kubernetes (common indicators)
is_kubernetes = (
    os.environ.get('KUBERNETES_SERVICE_HOST') is not None or
    os.environ.get('POSTGRES_HOST', '').endswith('.svc.cluster.local')
)

if os.environ.get('ALLOWED_HOSTS'):
    # Use explicit ALLOWED_HOSTS if set
    ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', '').split(',') if host.strip()]
elif is_kubernetes or DEBUG:
    # In Kubernetes or debug mode, allow all hosts (including pod IPs for health checks)
    # Django 5.1.7 supports '*' to allow all hosts
    ALLOWED_HOSTS = ['*']
else:
    # Production mode without ALLOWED_HOSTS set - allow all hosts for Kubernetes compatibility
    # This allows health checks to work while still being somewhat secure
    ALLOWED_HOSTS = ['*']  # In production, you should set ALLOWED_HOSTS env var explicitly


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'customer.apps.CustomerConfig',
    'product.apps.ProductConfig',
    'order.apps.OrderConfig',
    'rfm.apps.RfmConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'minicrm.middleware.KubernetesHealthCheckMiddleware',  # Must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'minicrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'minicrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Support both PostgreSQL (production) and SQLite (local development)
# PostgreSQL configuration via environment variables
# Supports both naming conventions:
# - Infrastructure convention: POSTGRES_HOST, POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
# - Generic convention: DB_ENGINE, DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT

# Check if PostgreSQL is configured (either via DB_ENGINE or POSTGRES_HOST)
use_postgresql = (
    os.environ.get('DB_ENGINE') == 'postgresql' or 
    os.environ.get('POSTGRES_HOST') is not None
)

if use_postgresql:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            # Support both naming conventions
            'NAME': os.environ.get('POSTGRES_DB') or os.environ.get('DB_NAME', 'minicrm'),
            'USER': os.environ.get('POSTGRES_USER') or os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD') or os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST') or os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT') or os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    # Default to SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT is required for collectstatic during S2I build
# S2I builder will collect static files to this directory
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
