# Generated by Django 5.1.7 on 2026-01-11 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFMScore',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rfm_score', serialize=False, to='customer.customer')),
                ('recency_days', models.IntegerField(help_text='Number of days since last order')),
                ('frequency', models.IntegerField(help_text='Total number of orders')),
                ('monetary', models.DecimalField(decimal_places=2, help_text='Total monetary value of all orders', max_digits=10)),
                ('recency_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Recency score (1-5), 5 = most recent')),
                ('frequency_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Frequency score (1-5), 5 = most frequent')),
                ('monetary_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Monetary score (1-5), 5 = highest value')),
                ('segment', models.CharField(choices=[('Champions', 'Champions - High value, frequent, recent customers'), ('Loyal Customers', 'Loyal Customers - Regular customers with good value'), ('Potential Loyalists', 'Potential Loyalists - Recent customers with potential'), ('New Customers', 'New Customers - Recent but low frequency/value'), ('Promising', 'Promising - Recent customers with moderate value'), ('Need Attention', 'Need Attention - Average customers at risk'), ('About to Sleep', 'About to Sleep - Low frequency, recent customers'), ('At Risk', 'At Risk - Previously frequent, now declining'), ('Cannot Lose Them', 'Cannot Lose Them - High value but infrequent'), ('Hibernating', 'Hibernating - Low activity, low value'), ('Lost', 'Lost - No recent activity, low value')], help_text='Customer segment based on RFM scores', max_length=50)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when RFM scores were calculated')),
            ],
            options={
                'verbose_name': 'RFM Score',
                'verbose_name_plural': 'RFM Scores',
                'db_table': 'rfm_scores',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
